pipeline {

    agent any

    tools {
        maven 'Maven3'
        jdk 'jdk21'
    }

    stages {

        stage('Checkout Code') {

            steps {

                git branch: 'main',
                url: 'https://github.com/Himanshusingh26202/Wipro_Capstone_Guru99-bank.git'
            }
        }

        stage('Build Project') {

            steps {

                dir('Guru99') {

                    bat 'mvn clean compile'
                }
            }
        }

        stage('Build Docker Image') {

            steps {

                dir('Guru99') {

                    bat 'docker build -t guru99-bank .'
                }
            }
        }

        stage('Run Tests in Docker') {

            steps {

                dir('Guru99') {

                    bat 'docker run --rm guru99-bank'
                }
            }
        }

        stage('Publish TestNG Results') {

            steps {

                dir('Guru99') {

                    junit 'test-output/junitreports/*.xml'
                }
            }
        }
    }

    post {

        always {

            archiveArtifacts(
                artifacts: 'Guru99/screenshots/*.png',
                allowEmptyArchive: true
            )

            archiveArtifacts(
                artifacts: 'Guru99/test-output/ExtentReport.html',
                allowEmptyArchive: true
            )
        }

        success {

            echo 'Guru99 Automation + Docker Execution Successful'
        }

        failure {

            echo 'Guru99 Automation + Docker Execution Failed'
        }
    }
}